# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDhyRTAq2o2W-A8mJTR8YbZQMOMVjA7x
"""

print('dia berkata : "pergilah!"')

print("aku menimpali: \"apakah kau ingin 'aku angkat kaki'\"!?")

print("\\(>_<)/) (\\-_-/)")
