# -*- coding: utf-8 -*-
"""Latihan 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10QhtYF8dYUD_ede3BYFd1dqRaIJdwzdi
"""

nama = 'lendis fabri'
usia = 20
lajang = True

print (type(nama))
print (type(usia))
print (type(lajang))

usia = input("masukkan usia anda : ")

print(type'usia')

panjang = input ('masukkan panjang :')
lebar = input ('masukkan lebar :')

a = 10/2

print(type(a))

b = 1/2

print(type(b))

kata = 'jeruk' = 5

print('kata')
print(type('kata'))

int()
float()

panjang = int(input ('masukkan panjang :'))
lebar = int(input ('masukkan lebar :'))

print('luas=', panjang * lebar)

nama = 'wudi'
tahun_lahir = 2000

print(nama + 'lahir di tahun' + str(tahun_lahir))